version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: postgres-user-management-db
    ports:
      - "5436:5432"
    environment:
      #      POSTGRES_USER_NAME: com_user_management_docker
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: user_management
    volumes:
      - E:\docker_volumes\postgres:/var/lib/postgresql-user-management/data
#  user-management-app:
#    image: ahmadaboualshamat/user-management
#    container_name: user-management-container
##    build: .
#    ports:
#      - "8080:8080"
#    deploy:
#      replicas: 1
##    expose:
##      - 8080
#    restart: always
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user_management
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 1234567
#      SPRING_LIQUIBASE_DROP-FIRST: false
#      SPRING_PROFILES_ACTIVE: qa