version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    container_name: postgres-user-management-db
    ports:
      - "5436:5432"
    environment:
      #      POSTGRES_USER_NAME: com_user_management_docker
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: user_management
    volumes:
      - /Users/ahmed.aboshamat/Documents/docker_volumes/postgres_users_db:/var/lib/postgresql-user-management/data
#    networks:
#      - user-management-network
  keyClock:
    container_name: key-cloak-container
    image: quay.io/keycloak/keycloak:24.0.2
#    networks:
#      - user-management
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - "start-dev"

#  user-management-app:
#    image: ahmadaboualshamat/user-management
#    container_name: user-management-container
##    build: .
#    ports:
#      - "8080:8080"
#    deploy:
#      replicas: 1
##    expose:
##      - 8080
#    restart: always
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user_management
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 1234567
#      SPRING_LIQUIBASE_DROP-FIRST: false
#      SPRING_PROFILES_ACTIVE: qa